export const PROJECTS = [
    { name: "Lap One", year: 2018, img: "/f1Scroll-optimized/1.jpg" },
    { name: "Pole Position", year: 2019, img: "/f1Scroll-optimized/2.jpg" },
    { name: "Pit Wall", year: 2020, img: "/f1Scroll-optimized/3.jpg" },
    { name: "Apex", year: 2021, img: "/f1Scroll-optimized/4.jpg" },
    { name: "Overcut", year: 2019, img: "/f1Scroll-optimized/5.jpg" },
    { name: "DRS Zone", year: 2022, img: "/f1Scroll-optimized/6.jpg" },
    { name: "Podium", year: 2020, img: "/f1Scroll-optimized/7.jpg" },
    { name: "Sector Three", year: 2021, img: "/f1Scroll-optimized/8.jpg" },
    { name: "Flat Out", year: 2018, img: "/f1Scroll-optimized/9.jpg" },
    { name: "Cold Tyres", year: 2023, img: "/f1Scroll-optimized/10.jpg" },
    { name: "Safety Car", year: 2022, img: "/f1Scroll-optimized/11.jpg" },
    { name: "Formation Lap", year: 2024, img: "/f1Scroll-optimized/12.jpg" },
    { name: "Checkered", year: 2019, img: "/f1Scroll-optimized/13.jpg" },
    { name: "Box Box Box", year: 2023, img: "/f1Scroll-optimized/14.jpg" },
    { name: "Silver Arrow", year: 2025, img: "/f1Scroll-optimized/15.jpg" },
    { name: "Final Lap", year: 2024, img: "/f1Scroll-optimized/16.jpg" },
]