import { Inter_Tight } from "next/font/google";
import "./globals.css";
import LenisSmoothScroll from "@/components/SmoothScroll/lenis";

const interTight = Inter_Tight({
    variable: "--font-inter-tight",
    subsets: ["latin"],
});

export const metadata = {
    title: "Abstract Cards",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${interTight.variable} h-full antialiased`}
        >
            <LenisSmoothScroll />
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}